productName = "GlanceMD"
version = "1.3.6"
identifier = "com.vastnext.glancemd"
description = "轻量级跨平台 Markdown 查看器与编辑器"
homepage = "https://github.com/VastNext/GlanceMD"
authors = ["VastNext"]
category = "Utility"
licenseFile = "LICENSE"
icons = ["assets/icon.png"]
outDir = "dist"

[[binaries]]
path = "GlanceMD"
main = true

[[fileAssociations]]
extensions = ["md", "markdown"]
mimeType = "text/markdown"
name = "Markdown Document"
role = "editor"

[[fileAssociations]]
extensions = ["txt"]
mimeType = "text/plain"
name = "Text Document"
role = "editor"

[linux]
generateDesktopEntry = true

[macos]
minimumSystemVersion = "10.13"
